[tool.poetry]
name = "pythonproject"
version = "0.1.0"
description = ""
authors = ["Rémi MEVAERE <git_commit@alias.mevaere.fr"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
